### ISSUE TITLE
TypeError: 'supportsAppend' is an unknown keyword argument

### ISSUE THREAD

**Issue by jonnyforestGIS** [Almeida100/RSC#1]
Hi @Almeida100, can you set  QGIS 3.14 as the minimum version of the plugin in metadata.txt.

supportsAppend parameter was introduced in 3.14 for QgsProcessingParameterFeatureSink

You have set as minimum version 3.0, So if someone uses an old version and try to install have the following error:
```python

 TypeError: 'supportsAppend' is an unknown keyword argument
```

Example:
https://qgis.org/pyqgis/3.10/core/QgsProcessingParameterFeatureSink.html?highlight=supportsappend - Don't have
https://qgis.org/pyqgis/3.12/core/QgsProcessingParameterFeatureSink.html?highlight=supportsappend - Don't have
https://qgis.org/pyqgis/3.14/core/QgsProcessingParameterFeatureSink.html?highlight=supportsappend - Have

Nice work.

Regards

**Comment by Almeida100** [comment]
Hi João,
Thank you very much for the suggestion.
Fixed in the QGis and GITHUB repositories.
Regards, Antonio Almeida
