### ISSUE TITLE
Algorithm ID outdated FieldCalculator

### ISSUE THREAD

**Issue by jonnyforestGIS** [Almeida100/RSC#2]
Hi @Almeida100,
you need to change this lines from **native:fieldcalculator** to **qgis:fieldcalculator**. See Algorithm ID:
https://docs.qgis.org/3.16/en/docs/user_manual/processing_algs/qgis/vectortable.html#field-calculator

https://github.com/Almeida100/RSC/blob/9e5d92dd25c662a8ca3a412977765207bf7258c1/road_slope_calculator_algorithm.py#L103

https://github.com/Almeida100/RSC/blob/9e5d92dd25c662a8ca3a412977765207bf7258c1/road_slope_calculator_algorithm.py#L119

I test and now works fine.
Regards

**Comment by Almeida100** [comment]
Thanks a lot. I developed this plugin on QGIS 3.16!
Regards, Antonio

A sexta, 12/03/2021, 15:00, João Gaspar ***@***.***> escreveu:
