### ISSUE TITLE
Plugin crashes QGIS

### ISSUE THREAD

**Issue by ShonzG** [Almeida100/RSC#4]
Every time I try and run the plugin, it crashes QGIS. What are the parameters I should be using? I there a max length for the line or a max area for the DEM?

**Comment by Almeida100** [comment]
Hello!
Can you send me a sample of the line layer and the DEM that crashes the
plugin?
If the DEM is larger that 20MB, please send it by WeTransfer (or other way).
Tell me what version of QGis and Windows you are using.
Regards
Antonio Almeida


ShonzG ***@***.***> escreveu no dia sábado, 5/03/2022 à(s)
05:34:

**Comment by elliots** [comment]
It crashed for me on an m1 mac, but didn't when run inside arm64 debian in parallels.

**Comment by spreaderman** [comment]
Crashes for me too on m2 mac.

**Comment by Almeida100** [comment]
Hi spreaderman

As elliots noted, this seems to be a problem with mxMac
On Windows10 with latest LTRs (3.22 and 3.28) this plugin works perfectly and very fast.
Regards

**Comment by Almeida100** [comment]
Since there was no further communication on this topic, I consider this issue closed.

**Comment by danlessa** [comment]
Crashes on my Mac M1 (Sonoma 14.2.1), using QGIS 3.28. I'm attaching an example DEM and GeoJSON 
[Archive.zip](https://github.com/Almeida100/Road-Slope-Calculator/files/14766499/Archive.zip)
